version: "3.6"

services:
    ens-data-source:
        image: dm3org/ens-bedrock-resolver:v0.1.0
        restart: always
        environment:
            L2_PROVIDER_URL: "$L2_PROVIDER_URL"
            L2_RESOLVER_ADDRESS: "$L2_RESOLVER_ADDRESS"
        ports:
            - "8887:8887"

    ccip-resolver:
        image: dm3org/ccip-resolver:v0.1.3
        restart: always
        environment:
            CONFIG: |
                {
                  "0xaeB973dA621Ed58F0D8bfD6299031E8a2Ac39FD4": {
                    "type": "optimism-bedrock",
                    "handlerUrl": "http://ens-data-source:8887",
                    "l1ProviderUrl": "$L1_PROVIDER_URL",
                    "l2ProviderUrl": "$L2_PROVIDER_URL",
                    "l1chainId": "5",
                    "l2chainId": "420"
                  }
                }
        ports:
            - "8081:8081"
